import { initNavigation } from "./components/navigation";
import { initGridSizePicker } from "./components/gridSizePicker";
import { initMosaicGrid } from "./components/mosaicGrid";
import { initSearch } from "./components/search";
import { initSave } from "./components/save";
import { initFillGaps } from "./components/fillGaps";
import { renderCollection } from "./components/collections";
import { initRandomizeCovers } from "./components/randomizeCovers";
import { initBuilderExport } from "./components/export";
import { initMosaicTitle } from "./components/builder";

initNavigation();
initGridSizePicker();
initMosaicGrid(4);
initSearch();
initSave();
initFillGaps();
initRandomizeCovers();
renderCollection();
initBuilderExport();
initMosaicTitle();